/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  IndexRes: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 第一阶段指标集合
     */
    firstStageIndexList?: definitions["FirstStageIndex"][];
    /**
     * 第二阶段指标集合
     */
    secondStageIndexList?: definitions["SecondStageIndex"][];
  };
  SearchExperimentMemberReq: {
    /**
     * 排序字段
     */
    column?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 搜索文本
     */
    searchText?: string;
    /**
     * 是否升序
     */
    sort?: boolean;
  };
  Materials: {
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 材料描述集合 @Transient
     */
    describeList?: definitions["MaterialsDescribe"][];
    /**
     * 主键ID
     */
    id?: string;
    materialsTypeId?: string;
    materialsTypeName?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 初始状态
     */
    originalState?: "有效" | "无效";
    /**
     * 图片路径
     */
    path?: string;
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 有效时间 (分钟)
     */
    validTime?: number;
  };
  MergeBusinessDescribeRequest: {
    /**
     * 描述
     */
    describeContent?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 名称
     */
    name?: string;
  };
  ExperimentClassMemberReq: { userId?: string };
  QueryCustomCaseListReq: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 搜索文本
     */
    searchText?: string;
  };
  BPhotoInfo: {
    /**
     * 账号
     */
    code?: string;
    /**
     * 图片相对地址
     */
    url?: string;
  };
  BusinessMerge: {
    /**
     * 业务并联id
     */
    businessInParallelId?: string;
    /**
     * 合并业务集合
     */
    businessList?: definitions["Business"][];
    /**
     * 业务类型id
     */
    businessTypeId?: string;
    /**
     * 业务类型名称
     */
    businessTypeName?: string;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    inParallel?: boolean;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "Map«string,List«Tool»»": { [key: string]: ref };
  OverallToolDepartmentReq: {
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  DeployResultRes: {
    /**
     * 指标图标
     */
    icon?: string;
    /**
     * 指标名称
     */
    name?: string;
    /**
     * 数量
     */
    num?: number;
    /**
     * 第二阶段指标id
     */
    secondStageIndexId?: string;
    /**
     * 指标单位
     */
    unit?: string;
  };
  UseOverallToolReq: {
    /**
     * 执行强度
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 全局工具使用部门集合
     */
    overallToolDepartmentList?: definitions["OverallToolDepartmentReq"][];
    /**
     * 工具id
     */
    stuToolId?: string;
    /**
     * 使用类型
     */
    useType?: string;
  };
  StuIncidentRecord: {
    complete?: boolean;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 事件描述
     */
    incidentDescribe?: string;
    /**
     * 事件id
     */
    incidentId?: string;
    /**
     * 事件名称
     */
    incidentName?: string;
    /**
     * 事件类型
     */
    incidentType?: string;
    /**
     * 事件选项id
     */
    operatingOptionId?: string;
    /**
     * 图标
     */
    path?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  ApkDownloadTask: {
    /**
     * 是否有版本更新
     */
    hasUpdate?: boolean;
    /**
     * apk文件下载地址
     */
    href?: string;
  };
  "公共REST返回Body对象«MergeWeightSecondStageIndexRequest»": {
    /**
     * 响应实体
     */
    data?: definitions["MergeWeightSecondStageIndexRequest"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ChangeUserInfoRequest: {
    /**
     * 年龄
     */
    age?: string;
    /**
     * 班级Id数组
     */
    classIds?: string;
    /**
     * 账号
     */
    code?: string;
    /**
     * 是否禁用(true or false)
     */
    disable?: string;
    /**
     * 新邮箱
     */
    email?: string;
    /**
     * 新姓名
     */
    name?: string;
    /**
     * 昵称
     */
    nickname?: string;
    /**
     * 生日
     */
    personalSignature?: string;
    /**
     * 个人简介
     */
    resume?: string;
    /**
     * 新自我介绍
     */
    selfIntroduction?: string;
    /**
     * 性别(0:女;1:男)
     */
    sex?: string;
    /**
     * 职业
     */
    title?: string;
  };
  "公共REST返回Body对象«MaterialsRes»": {
    /**
     * 响应实体
     */
    data?: definitions["MaterialsRes"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  SecondTaskFlow: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称 @Transient
     */
    mapDepartmentName?: string;
    /**
     * 第二阶段 并联部门集合
     */
    secondInParallelDepResList?: definitions["SecondInParallelDepRes"][];
    /**
     * 第二阶段 办事流程
     */
    secondTaskWorkFlowList?: definitions["SecondTaskWorkFlow"][];
    /**
     * 序号
     */
    seq?: number;
    /**
     * 第一阶段任务流程id
     */
    taskFlowId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "公共REST返回Body对象«List«TaskBackground»»": {
    /**
     * 响应实体
     */
    data?: definitions["TaskBackground"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeMaterialsDescribeRequest: {
    /**
     * 描述
     */
    describeContent: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 名称
     */
    name: string;
  };
  ExperimentClassReq: {
    /**
     * 班级id
     */
    classId?: string;
    /**
     * 班级下的用户
     */
    memberReqList?: definitions["ExperimentClassMemberReq"][];
    /**
     * 教师id
     */
    teacherId?: string;
  };
  ListClassMemberRequest: {
    /**
     * 班级名模糊查询
     */
    classNameLike?: string;
    /**
     * 班级Id
     */
    classRoom_uuid?: string;
    /**
     * 模糊查询（账号或姓名）
     */
    keyWord?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 教师Id
     */
    teacherId?: string;
    /**
     * 用户Id
     */
    userId?: string;
  };
  FirstStageIndex: {
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 指标图标
     */
    icon?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 描述
     */
    info?: string;
    /**
     * 指标名称
     */
    name?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  MergeAssessReq: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 指标id
     */
    indexId?: string;
    /**
     * 阶段
     */
    stage?: string;
    /**
     * 公式
     */
    targetFormula?: string;
    /**
     * 公式文本（展示给用户）
     */
    targetFormulaText?: string;
  };
  QueryStuTaskFlowReq: {
    createData?: boolean;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 任务流程id
     */
    taskFlowId?: string;
  };
  "BaseResponseBody«List«MapDepartment»»": {
    /**
     * 响应实体
     */
    data?: definitions["MapDepartment"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeBenefitRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 指标id
     */
    secondStageIndexId?: string;
    /**
     * 第二阶段指标名称
     */
    secondStageIndexName?: string;
    /**
     * 工具效益集合
     */
    toolBenefitResList?: definitions["ToolBenefitRequest"][];
  };
  PageQueryRequest: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  SoftConfigResult: {
    /**
     * copyRight Value
     */
    copyRightValue?: string;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 软件名称
     */
    softName?: string;
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 是否使用CAS登录(0 or 1)
     */
    useCas?: string;
  };
  QueryUserParam: {
    /**
     * 查询.是否禁用
     */
    disable?: string;
    /**
     * 查询.邮箱(模糊查询)
     */
    email?: string;
    /**
     * 查询.用户名称(模糊查询)
     */
    name?: string;
    /**
     * 查询.角色  0:学生;1:教师;2:管理员
     */
    role?: number;
    /**
     * 查询.用户代码(模糊查询)
     */
    userCode?: string;
  };
  "公共REST返回Body对象«RegionMap»": {
    /**
     * 响应实体
     */
    data?: definitions["RegionMap"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«PageResponse«TeacherMemberResp»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«TeacherMemberResp»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  DleIncidentRequest: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 事件类型
     */
    incidentType?: string;
    /**
     * 图片路径
     */
    path?: string;
  };
  "公共REST返回Body对象«List«Tool»»": {
    /**
     * 响应实体
     */
    data?: definitions["Tool"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«string»": {
    /**
     * 响应实体
     */
    data?: string;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  SearchDataCenterPageRequest: {
    /**
     * 排序字段
     */
    column?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 搜索文本
     */
    searchText?: string;
    /**
     * 是否升序
     */
    sort?: boolean;
    student?: boolean;
  };
  StuFlowUseTool: {
    /**
     * 耗费人力
     */
    consumeManpower?: number;
    /**
     * 耗费物力
     */
    consumeMaterial?: number;
    /**
     * 耗费技术
     */
    consumeTechnology?: number;
    /**
     * 耗费时间
     */
    consumeTime?: number;
    /**
     * 创建时间
     */
    createTime?: string;
    /**
     * 执行强度 初始值
     */
    executeInitValue?: number;
    /**
     * 执行强度 最大值
     */
    executeMaxValue?: number;
    /**
     * 执行强度 最小值
     */
    executeMinValue?: number;
    /**
     * 执行资金
     */
    executeMoney?: number;
    /**
     * 执行强度
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 购买资金
     */
    purchaseMoney?: number;
    /**
     * 节约行政成本
     */
    saveCost?: number;
    /**
     * 工具id
     */
    stuToolId?: string;
    /**
     * 学生工具对指标的影响
     */
    stuToolIndexNumRecordList?: definitions["StuToolIndexNumRecord"][];
    /**
     * 工具名称
     */
    toolName?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  UseFlowToolReq: {
    /**
     * 执行数值
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 学生工具id
     */
    stuToolId?: string;
  };
  QueryListToolWeightRequest: {
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 第二阶段指标id
     */
    secondStageIndexId?: string;
    /**
     * 第二阶段指标名称
     */
    secondStageIndexName?: string;
  };
  RegionMap: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门集合
     */
    mapDepartmentList?: definitions["MapDepartment"][];
    /**
     * 地图路径
     */
    path?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  DepartmentBenefitRequest: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 权重
     */
    weight?: number;
  };
  "公共REST返回Body对象«List«AllocationClass»»": {
    /**
     * 响应实体
     */
    data?: definitions["AllocationClass"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  Notification: {
    /**
     * 保存内容
     */
    content?: string;
    /**
     * 创建时间
     */
    createdTime?: string;
    /**
     * 主键ID
     */
    id?: string;
    read?: boolean;
    /**
     * 通知类型
     */
    type?: "分享资料" | "教师分配实训";
    /**
     * 收件人Id
     */
    userId?: string;
  };
  "BaseResponseBody«List«StuFlowDepOptionRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuFlowDepOptionRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«BusinessType»": {
    /**
     * 响应实体
     */
    data?: definitions["BusinessType"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QRLoginRequest: {
    /**
     * 二维码令牌
     */
    qrToken: string;
  };
  "BaseResponseBody«ApkDownloadTask»": {
    /**
     * 响应实体
     */
    data?: definitions["ApkDownloadTask"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeVariableFormulaRequest: {
    /**
     * 二级指标名称
     */
    secondStageIndexId?: string;
    /**
     * 公式
     */
    targetFormula?: string;
    /**
     * 公式文本（展示给用户）
     */
    targetFormulaText?: string;
  };
  "公共REST返回Body对象«IndexRes»": {
    /**
     * 响应实体
     */
    data?: definitions["IndexRes"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QueryClassRequest: {
    /**
     * 班级Id
     */
    id?: string;
    /**
     * 班级Ids
     */
    ids?: string[];
    /**
     * 模糊查询条件关键字
     */
    keyWord?: string;
    /**
     * 班级名称
     */
    name?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 是否升序/降序
     */
    seqAsc?: boolean;
    /**
     * 排序字段名
     */
    seqColumn?: string;
  };
  ExperimentMember: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 班级名称
     */
    className?: string;
    /**
     * 分配者名称
     */
    createUserName?: string;
    /**
     * 当前阶段
     */
    currentGeneration?: string;
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 案例名称
     */
    customCaseName?: string;
    /**
     * 结束时间
     */
    endTime?: string;
    /**
     * 进入时间
     */
    enterTime?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    firstEntry?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 排名
     */
    rank?: number;
    /**
     * 分数
     */
    score?: number;
    /**
     * 开始时间
     */
    startTime?: string;
    /**
     * 学生指标集合
     */
    stuSecondStageIndices?: definitions["StuSecondStageIndex"][];
    /**
     * 进行中/已结束
     */
    toState?: "进行中" | "已结束" | "未开始";
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 用户名称
     */
    userName?: string;
  };
  "公共REST返回Body对象«MergeIndexRequest»": {
    /**
     * 响应实体
     */
    data?: definitions["MergeIndexRequest"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QueryExperimentReq: {
    /**
     * 实训id
     */
    experimentId?: string;
  };
  CheckTokenRequest: { token: string };
  "PageResponse«TeacherMemberResp»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["TeacherMemberResp"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  StuFlowDepOptionRes: {
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 部门类别集合
     */
    stuFlowBusinessTypeOptionList?: definitions["StuFlowBusinessTypeOptionRes"][];
  };
  BackupMaterial: {
    createTime?: string;
    createUserId?: string;
    createUserName?: string;
    description?: string;
    fileUri?: string;
    /**
     * 主键ID
     */
    id?: string;
    seq?: number;
    title?: string;
    userId?: string;
  };
  BuildBusinessReq: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 业务名称
     */
    businessName?: string;
  };
  "BaseResponseBody«List«QueryStuToolRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["QueryStuToolRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«StuIncidentRecord»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuIncidentRecord"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ListTeacherMemberRequest: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 班级名模糊查询
     */
    classNameLike?: string;
    /**
     * 用户名模糊查询（账号或姓名）
     */
    keyWord?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 教师Id
     */
    teacherId?: string;
  };
  "公共REST返回Body对象«StuBusinessMergeInfo»": {
    /**
     * 响应实体
     */
    data?: definitions["StuBusinessMergeInfo"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeSecondTaskWorkFlowReq: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 数据id
     */
    id?: string;
    merge?: boolean;
    /**
     * 序号
     */
    seq?: number;
  };
  UpdateSecondGenerationReq: {
    /**
     * 案例id
     */
    customCaseId?: string;
    /**
     * 智能案例实训id
     */
    experimentId?: string;
  };
  QueryStuFlowDepOptionReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 当前部门id（用户点击当前房子或者修改业务 传值）
     */
    mapDepartmentId?: string;
    /**
     * 学生第二阶段流程id（用户点击加号传值）
     */
    stuSecondTaskFlowId?: string;
  };
  QueryStuToolRes: {
    /**
     * 列表标题
     */
    listTitle?: string;
    /**
     * 学生工具集合
     */
    stuToolList?: definitions["StuTool"][];
  };
  AllocationExperimentReq: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 自定义案例名称
     */
    customCaseName?: string;
    /**
     * 结束时间
     */
    endTime?: string;
    /**
     * 分配班级
     */
    experimentClassReqs?: definitions["ExperimentClassReq"][];
    /**
     * 第一阶段总时间
     */
    firstTotalTime?: number;
    /**
     * 第二阶段总时间
     */
    secondTotalTime?: number;
    /**
     * 开始时间
     */
    startTime?: string;
    /**
     * 查看答案
     */
    viewAnswer?: boolean;
    /**
     * 查看报告
     */
    viewReport?: boolean;
  };
  "BaseResponseBody«boolean»": {
    /**
     * 响应实体
     */
    data?: boolean;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ToolBenefitRequest: {
    /**
     * 部门效益集合
     */
    departmentBenefitList?: definitions["DepartmentBenefitRequest"][];
    /**
     * 工具id
     */
    toolId?: string;
    /**
     * 工具名称
     */
    toolName?: string;
  };
  "BaseResponseBody«long»": {
    /**
     * 响应实体
     */
    data?: number;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  OverallToolDepartment: {
    /**
     * 耗费人力
     */
    consumeManpower?: number;
    /**
     * 耗费物力
     */
    consumeMaterial?: number;
    /**
     * 耗费技术
     */
    consumeTechnology?: number;
    /**
     * 耗费时间
     */
    consumeTime?: number;
    /**
     * 执行强度 初始值
     */
    executeInitValue?: number;
    /**
     * 执行强度 最大值
     */
    executeMaxValue?: number;
    /**
     * 执行强度 最小值
     */
    executeMinValue?: number;
    /**
     * 执行资金
     */
    executeMoney?: number;
    /**
     * 执行强度
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 购买资金
     */
    purchaseMoney?: number;
    /**
     * 节约行政成本
     */
    saveCost?: number;
    /**
     * 学生全局工具使用id
     */
    stuOverallUseToolId?: string;
    /**
     * 工具id
     */
    stuToolId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  ForgetPasswordByMailRequest: {
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 用户账号
     */
    userCode?: string;
  };
  "公共REST返回Body对象«List«AssessRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["AssessRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  InParallelBusinessReq: {
    /**
     * 并联业务Id
     */
    inParallelBusinessId?: string;
    /**
     * 业务id
     */
    stuBusinessId?: string;
  };
  QueryUserRequest: {
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    queryParam?: definitions["QueryUserParam"];
  };
  BusinessType: {
    /**
     * 部门业务集合
     */
    businessList?: definitions["Business"][];
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "公共REST返回Body对象«PageResponse«ClassMember»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«ClassMember»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MapDepartment: {
    /**
     * 部门业务优化 是否完成
     */
    complete?: boolean;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门下标
     */
    indexNum?: string;
    /**
     * 部门信息
     */
    info?: string;
    /**
     * 初始人数
     */
    initNum?: number;
    /**
     * 业务 办结材料
     */
    materialsRelationRes?: definitions["MaterialsRelationRes"];
    /**
     * 业务 办结材料集合
     */
    materialsRelationResList?: definitions["MaterialsRelationRes"][];
    /**
     * 部门名称
     */
    name?: string;
    /**
     * 部门图片
     */
    path?: string;
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 办事效率
     */
    workEfficiency?: string;
  };
  TaskBackground: {
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 详情
     */
    info?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 类型
     */
    type?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "BaseResponseBody«List«DeployResultRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["DeployResultRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«Notification»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["Notification"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  StuTaskFlow: {
    complete?: boolean;
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    taskFlowId?: string;
    userId?: string;
  };
  "公共REST返回Body对象«List«StuBusiness»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuBusiness"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«CustomCase»": {
    /**
     * 响应实体
     */
    data?: definitions["CustomCase"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  SearchPageRequest: {
    /**
     * 排序字段
     */
    column?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 搜索文本
     */
    searchText?: string;
    /**
     * 是否升序
     */
    sort?: boolean;
  };
  "BaseResponseBody«List«BuildStuBusinessRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["BuildStuBusinessRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«StuSecondStageIndex»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuSecondStageIndex"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeIndexInfluenceRequest: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 数量
     */
    num?: number;
    /**
     * 结果
     */
    result?: string;
    /**
     * 第二阶段指标id
     */
    secondStageIndexId?: string;
  };
  MaterialsDescribe: {
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 描述
     */
    describeContent?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 材料id
     */
    materialsId?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  StuBusinessDescribeReq: {
    /**
     * 描述
     */
    describeContent?: string;
    /**
     * 名称
     */
    name?: string;
  };
  MergeSecondTaskFlowReq: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 第二阶段 并联部门办事流程
     */
    secondInParallelDepReqList?: definitions["SecondInParallelDepReq"][];
    /**
     * 第二阶段 办事流程
     */
    secondTaskWorkFlowReqList?: definitions["MergeSecondTaskWorkFlowReq"][];
    /**
     * 序号
     */
    seq?: number;
    /**
     * 第一阶段任务流程id
     */
    taskFlowId?: string;
  };
  Business: {
    /**
     * 现状描述集合
     */
    actualityDescribeList?: definitions["BusinessDescribe"][];
    /**
     * 是否可删
     */
    allowDelete?: boolean;
    /**
     * 业务表单集合
     */
    businessFlowFormList?: definitions["BusinessFlowForm"][];
    /**
     * 业务并联id
     */
    businessInParallelId?: string;
    /**
     * 业务合并id
     */
    businessMergeId?: string;
    /**
     * 业务合并名称
     */
    businessMergeName?: string;
    /**
     * 业务类型id
     */
    businessTypeId?: string;
    /**
     * 业务类型名称
     */
    businessTypeName?: string;
    /**
     * 办结材料合
     */
    concludeMaterialsList?: definitions["BusinessMaterialsRelation"][];
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 办理费用
     */
    expense?: number;
    /**
     * 办理指南集合
     */
    guideDescribeList?: definitions["BusinessDescribe"][];
    /**
     * 主键ID
     */
    id?: string;
    inParallel?: boolean;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    merge?: boolean;
    /**
     * 名称
     */
    name?: string;
    /**
     * 实际耗时
     */
    practicalConsumeTime?: number;
    /**
     * 所需材料集合
     */
    requiredMaterialsList?: definitions["BusinessMaterialsRelation"][];
    /**
     * 软件耗时
     */
    softwareConsumeTime?: number;
    /**
     * 用户id
     */
    userId?: string;
  };
  StuToolIndexNumRecord: {
    createTime?: string;
    /**
     * 执行强度
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 数量
     */
    num?: number;
    /**
     * 第二阶段指标id
     */
    secondStageIndexId?: string;
    /**
     * 学生部门工具使用id
     */
    stuDepartmentUseToolId?: string;
    /**
     * 学生流程工具使用id
     */
    stuFlowUseToolId?: string;
    /**
     * 学生事件记录id
     */
    stuIncidentRecordId?: string;
    /**
     * 学生全局工具使用id
     */
    stuOverallUseToolId?: string;
    /**
     * 工具id
     */
    stuToolId?: string;
    /**
     * 工具名称
     */
    toolName?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  ShopToolReq: {
    /**
     * 实验id
     */
    experimentId: string;
    /**
     * 购买金额
     */
    purchaseMoney: number;
    /**
     * 学生工具id
     */
    stuToolId: string;
  };
  StuBusinessOptimizeRecord: {
    /**
     * 业务名称
     */
    businessName?: string;
  };
  "BaseResponseBody«PageResponse«Notification»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«Notification»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  GetExperimentMemberInfoReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  "BaseResponseBody«List«BuildBusinessDescribeRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["BuildBusinessDescribeRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«SecondStageWeightRes»": {
    /**
     * 响应实体
     */
    data?: definitions["SecondStageWeightRes"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ListMapDepartmentReq: {
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 实训id
     */
    experimentId?: string;
  };
  StuOverallUseTool: {
    /**
     * 耗费人力 非持久化
     */
    consumeManpower?: number;
    /**
     * 耗费物力 非持久化
     */
    consumeMaterial?: number;
    /**
     * 耗费技术 非持久化
     */
    consumeTechnology?: number;
    /**
     * 耗费时间 非持久化
     */
    consumeTime?: number;
    /**
     * 创建时间
     */
    createTime?: string;
    /**
     * 执行强度 初始值 非持久化
     */
    executeInitValue?: number;
    /**
     * 执行强度 最大值 非持久化
     */
    executeMaxValue?: number;
    /**
     * 执行强度 最小值 非持久化
     */
    executeMinValue?: number;
    /**
     * 执行资金 非持久化
     */
    executeMoney?: number;
    /**
     * 执行强度
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 全局部门工具集合 非持久化
     */
    overallToolDepartmentList?: definitions["OverallToolDepartment"][];
    /**
     * 购买资金 非持久化
     */
    purchaseMoney?: number;
    /**
     * 节约行政成本 非持久化
     */
    saveCost?: number;
    /**
     * 工具id
     */
    stuToolId?: string;
    /**
     * 学生工具对指标的影响
     */
    stuToolIndexNumRecordList?: definitions["StuToolIndexNumRecord"][];
    /**
     * 工具名称
     */
    toolName?: string;
    /**
     * 使用类型
     */
    useType?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  UpdateStuTaskWorkFlowReq: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 是否是合并业务
     */
    merge?: boolean;
    /**
     * 学生业务id
     */
    stuBusinessId?: string;
  };
  "公共REST返回Body对象«BusinessMerge»": {
    /**
     * 响应实体
     */
    data?: definitions["BusinessMerge"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeClassRequest: {
    /**
     * 是否禁用
     */
    disable?: boolean;
    /**
     * 主键Id
     */
    id?: string;
    /**
     * 班级名称
     */
    name: string;
    /**
     * 备注
     */
    remarks?: string;
    /**
     * 管理老师账号，不传则不变
     */
    teacherCodes?: string;
  };
  StuBusinessMergeInfo: {
    /**
     * 办理费用
     */
    expense?: number;
    /**
     * 办理指南集合
     */
    guideDescribeList?: definitions["StuBusinessDescribe"][];
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 办理周期
     */
    manageConsumeTime?: number;
    /**
     * 反馈材料
     */
    materials?: string;
    /**
     * 所需材料
     */
    materialsType?: string;
    /**
     * 合并业务id
     */
    stuBusinessId?: string;
  };
  MergeTaskBackgroundRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 详情
     */
    info?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 类型
     */
    type?: string;
  };
  ListToolRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 列表标题
     */
    listTitle?: string;
  };
  PreciseExperimentMemberReq: {
    /**
     * 排序字段
     */
    column?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 搜索文本
     */
    searchText?: string;
    /**
     * 是否升序
     */
    sort?: boolean;
  };
  UseMapDepartmentToolReq: {
    /**
     * 执行数值
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 学生工具id
     */
    stuToolId?: string;
  };
  QueryDepartmentBusinessReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  MergeNumDepartmentReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    merge?: boolean;
    /**
     * 序号
     */
    seq?: number;
    /**
     * 原部门id
     */
    srcMapDepartmentId?: string;
    /**
     * 学生业务id
     */
    stuBusinessId?: string;
    /**
     * 任务流程id
     */
    taskFlowId?: string;
  };
  "公共REST返回Body对象«List«MergeTaskFlowRequest»»": {
    /**
     * 响应实体
     */
    data?: definitions["MergeTaskFlowRequest"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  Class: {
    /**
     * 禁用
     */
    disable?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 班级名称
     */
    name?: string;
    /**
     * 备注
     */
    remarks?: string;
    /**
     * 学生人数 @Transient
     */
    stuNum?: number;
    /**
     * 老师ID @Transient
     */
    teacherCodes?: string;
    /**
     * 老师名称 @Transient
     */
    userNames?: string;
    /**
     * 是否是教师、管理员专用班级
     */
    vipClass?: boolean;
  };
  BatchMergeMapDepartmentReq: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门下标
     */
    index?: string;
    /**
     * 部门信息
     */
    info?: string;
    /**
     * 部门名称
     */
    name?: string;
  };
  "公共REST返回Body对象«List«MapDepartmentBusinessRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["MapDepartmentBusinessRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«List«MapDepartment»»": {
    /**
     * 响应实体
     */
    data?: definitions["MapDepartment"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  RteUploadResponse: {
    /**
     * 文件名称
     */
    fileName?: string;
    /**
     * 文件是否成功
     */
    uploaded?: number;
    /**
     * 文件路径
     */
    url?: string;
  };
  MapDepartmentBusinessRes: {
    /**
     * 业务类别集合
     */
    businessTypeList?: definitions["BusinessTypeRes"][];
    /**
     * 部门id
     */
    id?: string;
    /**
     * 部门名称
     */
    name?: string;
  };
  "Map«string,Map«string,List«Tool»»»": { [key: string]: ref };
  "BaseResponseBody«LoginUserResponse»": {
    /**
     * 响应实体
     */
    data?: definitions["LoginUserResponse"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«PageResponse«ExperimentMember»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«ExperimentMember»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«int»": {
    /**
     * 响应实体
     */
    data?: number;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StuBusinessDescribe: {
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 描述
     */
    describeContent?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 合并业务id
     */
    stuBusinessId?: string;
    /**
     * 描述类型
     */
    type?: string;
  };
  ChangePasswordRequest: {
    /**
     * 账号
     */
    code: string;
    /**
     * 新密码
     */
    newPassword?: string;
    /**
     * 原密码
     */
    oldPassword?: string;
  };
  BusinessRes: {
    /**
     * 业务 办结材料集合
     */
    concludeMaterialsList?: definitions["MaterialsRelationRes"][];
    /**
     * 业务id
     */
    id?: string;
    merge?: boolean;
    /**
     * 业务名称
     */
    name?: string;
    /**
     * 业务 所需材料集合
     */
    requiredMaterialsList?: definitions["MaterialsRelationRes"][];
  };
  "公共REST返回Body对象«Assess»": {
    /**
     * 响应实体
     */
    data?: definitions["Assess"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  BusinessDescribe: {
    /**
     * 材料id
     */
    businessId?: string;
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 描述
     */
    describeContent?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 描述类型
     */
    type?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  MergeBusinessInParallelReq: {
    /**
     * 并联业务集合
     */
    buildBusinessInParallelReqs?: definitions["BuildBusinessInParallelReq"][];
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  TaskWorkFlow: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 合并业务id @Transient
     */
    businessMergeId?: string;
    /**
     * 合并业务名称 @Transient
     */
    businessMergeName?: string;
    /**
     * 业务名称 @Transient
     */
    businessName?: string;
    /**
     * 业务类别
     */
    businessTypeId?: string;
    /**
     * 办结材料集合 @Transient
     */
    concludeMaterialsList?: definitions["MaterialsRelationRes"][];
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称 @Transient
     */
    mapDepartmentName?: string;
    merge?: boolean;
    /**
     * 所需材料集合  @Transient
     */
    requiredMaterialsList?: definitions["MaterialsRelationRes"][];
    /**
     * 流程id
     */
    taskFlowId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  TeacherMemberResp: {
    /**
     * 管理班级id数组
     */
    classIds?: string;
    /**
     * 管理班级名称数组
     */
    classNames?: string;
    /**
     * 教师头像
     */
    headPath?: string;
    /**
     * 是否禁用
     */
    userDisable?: boolean;
    /**
     * 教师账号
     */
    userId?: string;
    /**
     * 教师名称
     */
    userName?: string;
  };
  MergeSecondStageIndexRequest: {
    /**
     * 指标图标
     */
    icon?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 描述
     */
    info?: string;
    /**
     * 初始值
     */
    initValue?: number;
    /**
     * 最大值
     */
    maxValue?: number;
    /**
     * 最小值
     */
    minValue?: number;
    /**
     * 指标名称
     */
    name?: string;
    /**
     * 指标单位
     */
    unit?: string;
  };
  "BaseResponseBody«List«StuSecondTaskFlow»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuSecondTaskFlow"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StuSecondTaskWorkFlow: {
    /**
     * 是否可删
     */
    allowDelete?: boolean;
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 办结材料集合 @Transient
     */
    concludeMaterialsList?: definitions["MaterialsRelationRes"][];
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    inParallel?: boolean;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 学生合并业务反馈材料 @Transient
     */
    materials?: string;
    /**
     * 学生合并业务所需材料 @Transient
     */
    materialsType?: string;
    merge?: boolean;
    /**
     * 所需材料集合  @Transient
     */
    requiredMaterialsList?: definitions["MaterialsRelationRes"][];
    /**
     * 学生业务id
     */
    stuBusinessId?: string;
    /**
     * 业务名称
     */
    stuBusinessName?: string;
    /**
     * 学生第二阶段流程id
     */
    stuSecondTaskFlowId?: string;
    /**
     * 第一阶段任务流程id
     */
    taskFlowId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  DelNumDepartmentBusinessReq: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  CreateOrUpdateClassMemberRequest: {
    /**
     * 班级Id
     */
    classId: string;
    /**
     * 是否教师
     */
    isTeacher?: string;
    /**
     * 用户名称
     */
    name?: string;
    /**
     * 学员Id
     */
    userId: string;
  };
  UserLoginHistory: {
    /**
     * 班级名称@Transient
     */
    className?: string;
    /**
     * 电子邮箱
     */
    email?: string;
    /**
     * 登录失败历史
     */
    failed?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 登录地址
     */
    loginAddr?: string;
    loginIp?: string;
    /**
     * 登录时间
     */
    loginTime?: string;
    /**
     * 用户名
     */
    name?: string;
    /**
     * 用户code
     */
    userCode?: string;
  };
  CustomCase: {
    /**
     * 创建时间
     */
    createTime?: string;
    /**
     * 第一阶段区间范围
     */
    firstScope?: number;
    /**
     * 第一阶段时间
     */
    firstTime?: string;
    /**
     * 第一阶段总时间 非持久化
     */
    firstTotalTime?: number;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 案例简介
     */
    info?: string;
    /**
     * 案例名称
     */
    name?: string;
    /**
     * 案例图片path
     */
    path?: string;
    /**
     * 人口密度
     */
    populationDensity?: number;
    publish?: boolean;
    /**
     * 第二阶段区间范围
     */
    secondScope?: number;
    /**
     * 第二阶段时间
     */
    secondTime?: string;
    /**
     * 第二阶段总时间 非持久化
     */
    secondTotalTime?: number;
    /**
     * 案例类型
     */
    type?: string;
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 用户名称
     */
    userName?: string;
  };
  StuBusinessReq: {
    /**
     * 学生业务id
     */
    stuBusinessId?: string;
  };
  LoginUserResponse: {
    /**
     * 用户号
     */
    code?: string;
    disable?: boolean;
    /**
     * 姓名
     */
    name?: string;
    /**
     * 角色(admin;teacher;student)
     */
    role?: string;
    token?: string;
  };
  StuTool: {
    /**
     * 案例id
     */
    customCaseId?: string;
    /**
     * 工具执行强度
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 工具介绍
     */
    info?: string;
    /**
     * 等级
     */
    level?: string;
    /**
     * 列表标题
     */
    listTitle?: string;
    /**
     * 工具名称
     */
    name?: string;
    /**
     * 图片路径
     */
    path?: string;
    /**
     * 属性
     */
    property?: string;
    /**
     * 购买资金
     */
    purchaseMoney?: number;
    /**
     * 状态
     */
    state?: string;
    /**
     * 部门工具 详情
     */
    stuDepartmentUseTool?: definitions["StuDepartmentUseTool"];
    /**
     * 流程工具 详情
     */
    stuFlowUseTool?: definitions["StuFlowUseTool"];
    /**
     * 全局工具 详情
     */
    stuOverallUseTool?: definitions["StuOverallUseTool"];
    /**
     * 工具id
     */
    toolId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  UpdateMapDepartmentRequest: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 初始人数
     */
    initNum?: number;
    /**
     * 图片路径
     */
    path?: string;
    /**
     * 办事效率
     */
    workEfficiency?: string;
  };
  MergeBusinessTypeRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 名称
     */
    name?: string;
  };
  "BaseResponseBody«BackupMaterial»": {
    /**
     * 响应实体
     */
    data?: definitions["BackupMaterial"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«Class»": {
    /**
     * 响应实体
     */
    data?: definitions["Class"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  GetOperatingOptionReq: {
    /**
     * 事件id
     */
    incidentId?: string;
  };
  MapDepartmentReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  BusinessMaterialsRelation: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 材料id
     */
    materialsId?: string;
    /**
     * 材料名称 @Transient
     */
    materialsName?: string;
    /**
     * 类别
     */
    type?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "BaseResponseBody«Void»": {
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  TaskBackgroundReq: {
    /**
     * 案例id
     */
    customCaseId?: string;
    /**
     * 类型
     */
    type?: string;
  };
  Assess: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 指标id
     */
    indexId?: string;
    /**
     * 指标名称
     */
    indexName?: string;
    /**
     * 学生对应指标数值
     */
    num?: number;
    /**
     * 阶段
     */
    stage?: string;
    /**
     * 学生对应指标id
     */
    stuSecondStageIndexId?: string;
    /**
     * 公式
     */
    targetFormula?: string;
    /**
     * 公式文本（展示给用户）
     */
    targetFormulaText?: string;
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 权重
     */
    weight?: number;
  };
  MergeWebLinkReq: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 链接
     */
    link: string;
    /**
     * 序号
     */
    seq: number;
    /**
     * 标题
     */
    title: string;
  };
  UserQRLoginRecord: {
    /**
     * 角色.是否是管理员@Transient
     */
    admin?: boolean;
    /**
     * 创建时间
     */
    createTime?: string;
    /**
     * 失效时间
     */
    expireTime?: string;
    /**
     * 二维码图片地址
     */
    qrImagePath?: string;
    /**
     * 二维码图片Baser64码
     */
    qrImagePathBase64?: string;
    /**
     * 二维码令牌
     */
    qrToken?: string;
    /**
     * 状态,选项为:0:开始;1:手机已扫码;999:手机已登录;-999:二维码失效
     */
    state?: number;
    /**
     * 角色.是否是教师@Transient
     */
    teacher?: boolean;
    /**
     * 登录成功后用户token
     */
    token?: string;
    /**
     * 用户对象@Transient
     */
    userId?: string;
  };
  UpdateAssessWeightReq: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 维度
     */
    weight?: number;
  };
  "BaseResponseBody«StuSecondTaskFlow»": {
    /**
     * 响应实体
     */
    data?: definitions["StuSecondTaskFlow"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ChangeUserRoleRequest: {
    /**
     * 是否是管理员
     */
    admin?: boolean;
    /**
     * 账号
     */
    code?: string;
    /**
     * 是否是学生
     */
    student?: boolean;
    /**
     * 是否是教师
     */
    teacher?: boolean;
  };
  QueryLoginHistoryRequest: {
    /**
     * 查询.用户邮箱
     */
    email?: string;
    /**
     * 查询.登录结束时间
     */
    endTime?: number;
    /**
     * 查询.用户姓名
     */
    name?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
    /**
     * 查询.登录开始时间
     */
    startTime?: number;
    /**
     * 查询.用户号
     */
    userCode?: string;
  };
  "公共REST返回Body对象«int»": {
    /**
     * 响应实体
     */
    data?: number;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  DeleteRequest: {
    /**
     * 数据id
     */
    id?: string;
  };
  "公共REST返回Body对象«Map«string,Map«string,List«Tool»»»»": {
    /**
     * 响应实体
     */
    data?: { [key: string]: object };
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«ClassMember»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["ClassMember"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  DelInParallelDepartmentReq: {
    /**
     * 部门
     */
    mapDepartmentId?: string;
    /**
     * 第二阶段流程id
     */
    secondTaskFlowId?: string;
  };
  QueryTaskFlowReq: {
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 实训id
     */
    experimentId?: string;
  };
  TaskFlow: {
    /**
     * 学生流程任务是否完成 true/false
     */
    complete?: boolean;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 流程名称
     */
    name?: string;
    /**
     * 任务部门集合
     */
    taskMapDepartmentList?: definitions["TaskMapDepartmentRes"][];
    /**
     * 用户id
     */
    userId?: string;
  };
  QueryCustomCaseRequest: {
    /**
     * 自定义id
     */
    customCaseId?: string;
  };
  QuerySecondFlowReq: {
    /**
     * 第一阶段 流程id
     */
    taskFlowId?: string;
  };
  MergeTaskWorkFlowRequest: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 业务名称
     */
    businessName?: string;
    /**
     * （办结）/（反馈）材料集合
     */
    concludeMaterialsList?: definitions["BuildMaterialsRequest"][];
    /**
     * 数据id
     */
    id?: string;
    /**
     * 所需材料集合
     */
    requiredMaterialsList?: definitions["BuildMaterialsRequest"][];
  };
  BusinessInParallel: {
    /**
     * 并联部门集合
     */
    buildBusinessInParallelResList?: definitions["BuildBusinessInParallelRes"][];
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "公共REST返回Body对象«Incident»": {
    /**
     * 响应实体
     */
    data?: definitions["Incident"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«MergeBenefitRequest»": {
    /**
     * 响应实体
     */
    data?: definitions["MergeBenefitRequest"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«UserQRLoginRecord»": {
    /**
     * 响应实体
     */
    data?: definitions["UserQRLoginRecord"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  UpdatePublishRequest: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 是否发布
     */
    publish?: boolean;
  };
  "BaseResponseBody«ProfessionalTerm»": {
    /**
     * 响应实体
     */
    data?: definitions["ProfessionalTerm"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«OperatingOption»»": {
    /**
     * 响应实体
     */
    data?: definitions["OperatingOption"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QueryStuDataReq: {
    /**
     * 实训id
     */
    experimentId?: string;
  };
  DelTaskWorkFlowReq: {
    /**
     * 任务流程id
     */
    taskFlowId: string;
  };
  BatchUpdateNumReq: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 序号
     */
    seq?: number;
  };
  "BaseResponseBody«ExperimentMemberInfo»": {
    /**
     * 响应实体
     */
    data?: definitions["ExperimentMemberInfo"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«List«SecondStageIndex»»": {
    /**
     * 响应实体
     */
    data?: definitions["SecondStageIndex"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«List«StuBusinessOptimizeType»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuBusinessOptimizeType"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeFirstStageIndexRequest: {
    /**
     * 指标图标
     */
    icon?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 描述
     */
    info?: string;
    /**
     * 指标名称
     */
    name?: string;
  };
  GetByIdRequest: {
    /**
     * id
     */
    id: string;
  };
  "BaseResponseBody«StuTaskFlow»": {
    /**
     * 响应实体
     */
    data?: definitions["StuTaskFlow"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  InParallelStuBusinessReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 并联业务集合
     */
    stuBusinessReqList?: definitions["StuBusinessReq"][];
  };
  BusinessTypeRes: {
    /**
     * 业务集合
     */
    businessesList?: definitions["BusinessRes"][];
    /**
     * 业务类别id
     */
    id?: string;
    /**
     * 业务类别名称
     */
    name?: string;
  };
  "公共REST返回Body对象«PageResponse«CustomCase»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«CustomCase»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«SecondStageBenefitRes»": {
    /**
     * 响应实体
     */
    data?: definitions["SecondStageBenefitRes"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StuSecondInParallelDepRes: {
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 第二阶段 并联办事流程
     */
    stuSecondTaskInParallelWorkFlowList?: definitions["StuSecondTaskWorkFlow"][];
  };
  "公共REST返回Body对象«ClassMember»": {
    /**
     * 响应实体
     */
    data?: definitions["ClassMember"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«List«MergeToolRequest»»": {
    /**
     * 响应实体
     */
    data?: definitions["MergeToolRequest"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ShareDataReq: {
    ids?: definitions["JSONArray"];
    /**
     * 是否分享给所有教师 (默认false)
     */
    shareAll?: boolean;
    /**
     * 分享给部分用户
     */
    toUsers?: definitions["JSONArray"];
  };
  SearchTopologicalGraphReq: {
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 搜索文本
     */
    searchText?: string;
  };
  "公共REST返回Body对象«List«BusinessInParallel»»": {
    /**
     * 响应实体
     */
    data?: definitions["BusinessInParallel"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StuBusinessOptimizeType: {
    /**
     * 优化记录集合
     */
    optimizeRecordList?: definitions["StuBusinessOptimizeRecord"][];
    /**
     * 类型
     */
    type?: string;
  };
  "PageResponse«CustomCase»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["CustomCase"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  ExportExcelReq: {
    /**
     * 班级id
     */
    classId?: string;
    /**
     * 实训id
     */
    experimentId?: string;
  };
  "公共REST返回Body对象«MaterialsType»": {
    /**
     * 响应实体
     */
    data?: definitions["MaterialsType"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  SecondInParallelDepReq: {
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId: string;
    /**
     * 第二阶段 并联办事流程
     */
    secondTaskInParallelWorkFlowReqList?: definitions["MergeSecondTaskWorkFlowReq"][];
  };
  BuildBusinessInParallelReq: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 业务名称
     */
    businessName?: string;
    merge?: boolean;
  };
  BuildBusinessInParallelRes: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 合并子业务集合
     */
    businessList?: definitions["Business"][];
    /**
     * 业务名称
     */
    businessName?: string;
    /**
     * 业务类型Id
     */
    businessTypeId?: string;
    /**
     * 业务类型名称
     */
    businessTypeName?: string;
    merge?: boolean;
  };
  "BaseResponseBody«User»": {
    /**
     * 响应实体
     */
    data?: definitions["User"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeWeightRequest: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 工具id
     */
    toolId?: string;
    /**
     * 工具名称
     */
    toolName?: string;
    /**
     * 权重
     */
    weight?: number;
  };
  BusinessFlowForm: {
    /**
     * 后表单
     */
    afterForm?: string;
    /**
     * 前表单
     */
    beforeForm?: string;
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  MaterialsType: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  MergeWeightSecondStageIndexRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 指标id
     */
    secondStageIndexId?: string;
    /**
     * 第二阶段指标名称
     */
    secondStageIndexName?: string;
    /**
     * 工具权重集合
     */
    toolWeightList?: definitions["MergeWeightRequest"][];
  };
  MaterialsRes: {
    /**
     * 材料内容集合
     */
    materials?: definitions["Materials"][];
    /**
     * 材料类别集合
     */
    materialsTypes?: definitions["MaterialsType"][];
  };
  MergeIncidentRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 事件描述
     */
    incidentDescribe?: string;
    /**
     * 事件类型
     */
    incidentType?: string;
    /**
     * 指标影响集合
     */
    indexInfluenceList?: definitions["MergeIndexInfluenceRequest"][];
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 选项集合
     */
    operatingOptionList?: definitions["MergeOperatingOptionRequest"][];
    /**
     * 图片路径
     */
    path?: string;
    /**
     * 第二阶段指标id（条件公式中的变量）
     */
    secondStageIndexId?: string;
    /**
     * 条件公式
     */
    targetFormula?: string;
    /**
     * 触发条件
     */
    triggerCondition?: string;
    /**
     * 触发时间
     */
    triggerTime?: number;
  };
  DelMaterialReq: {
    /**
     * 老路劲
     */
    fileUri: string;
    /**
     * 数据id
     */
    id: string;
  };
  "BaseResponseBody«string»": {
    /**
     * 响应实体
     */
    data?: string;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StuDepartmentUseTool: {
    /**
     * 耗费人力
     */
    consumeManpower?: number;
    /**
     * 耗费物力
     */
    consumeMaterial?: number;
    /**
     * 耗费技术
     */
    consumeTechnology?: number;
    /**
     * 耗费时间
     */
    consumeTime?: number;
    /**
     * 创建时间
     */
    createTime?: string;
    /**
     * 执行强度 初始值
     */
    executeInitValue?: number;
    /**
     * 执行强度 最大值
     */
    executeMaxValue?: number;
    /**
     * 执行强度 最小值
     */
    executeMinValue?: number;
    /**
     * 执行资金
     */
    executeMoney?: number;
    /**
     * 执行强度
     */
    executeValue?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 购买资金
     */
    purchaseMoney?: number;
    /**
     * 节约行政成本
     */
    saveCost?: number;
    /**
     * 工具id
     */
    stuToolId?: string;
    /**
     * 工具对指标记录
     */
    targetToolIndexNumRecordList?: definitions["StuToolIndexNumRecord"][];
    /**
     * 业务名称
     */
    toolName?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  UpdateAllowDeleteRequest: {
    /**
     * 是否允许删除
     */
    allowDelete?: boolean;
    /**
     * 数据id
     */
    id?: string;
  };
  DelToolRequest: {
    /**
     * 数据id
     */
    id?: string;
    /**
     * 图片路径
     */
    path?: string;
  };
  UpdateMaterialReq: {
    /**
     * 简介
     */
    description?: string;
    /**
     * id
     */
    id?: string;
    /**
     * 排序
     */
    seq?: number;
    /**
     * title
     */
    title?: string;
  };
  StuSecondStageIndex: {
    /**
     * 用户id
     */
    experimentId?: string;
    /**
     * 指标图标
     */
    icon?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 描述
     */
    info?: string;
    /**
     * 指标名称
     */
    name?: string;
    /**
     * 数量
     */
    num?: number;
    /**
     * 指标分数
     */
    score?: number;
    /**
     * 第二阶段指标id
     */
    secondStageIndexId?: string;
    /**
     * 指标单位
     */
    unit?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "PageResponse«Experiment»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["Experiment"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  SecondInParallelDepRes: {
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 第二阶段 并联办事流程
     */
    secondTaskInParallelWorkFlowList?: definitions["SecondTaskWorkFlow"][];
  };
  SecondStageIndex: {
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 执行强度所选工具id @Transient
     */
    executeToolId?: string;
    /**
     * 学生执行强度数值 @Transient
     */
    executeWeightNum?: number;
    /**
     * 指标图标
     */
    icon?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 描述
     */
    info?: string;
    /**
     * 初始值
     */
    initValue?: number;
    /**
     * 最大值
     */
    maxValue?: number;
    /**
     * 最小值
     */
    minValue?: number;
    /**
     * 指标名称
     */
    name?: string;
    /**
     * 对应学生使用工具 @Transient
     */
    stuDepartmentUseTool?: definitions["StuDepartmentUseTool"];
    /**
     * 对应学生指标 @Transient
     */
    stuSecondStageIndex?: definitions["StuSecondStageIndex"];
    /**
     * 公式
     */
    targetFormula?: string;
    /**
     * 公式文本（展示给用户）
     */
    targetFormulaText?: string;
    /**
     * 指标单位
     */
    unit?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "公共REST返回Body对象«BusinessFlowForm»": {
    /**
     * 响应实体
     */
    data?: definitions["BusinessFlowForm"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ExperimentMemberInfo: {
    /**
     * 学生实训分页集合
     */
    experimentMemberPageResponse?: definitions["PageResponse«ExperimentMember»"];
    /**
     * 排名
     */
    rank?: number;
  };
  MergeBusinessRequest: {
    /**
     * 现状描述集合
     */
    actualityDescribeList?: definitions["MergeBusinessDescribeRequest"][];
    /**
     * 业务类型id
     */
    businessTypeId: string;
    /**
     * 办结材料集合
     */
    concludeMaterialsList?: definitions["BuildMaterialsRequest"][];
    /**
     * 自定义案例id
     */
    customCaseId: string;
    /**
     * 办理费用
     */
    expense: number;
    /**
     * 办理指南集合
     */
    guideDescribeList?: definitions["MergeBusinessDescribeRequest"][];
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId: string;
    /**
     * 业务流程表单集合
     */
    mergeBusinessFlowFormList?: definitions["MergeBusinessFlowForm"][];
    /**
     * 名称
     */
    name: string;
    /**
     * 实际耗时
     */
    practicalConsumeTime: number;
    /**
     * 所需材料集合
     */
    requiredMaterialsList?: definitions["BuildMaterialsRequest"][];
    /**
     * 软件耗时
     */
    softwareConsumeTime: number;
  };
  "BaseResponseBody«List«User»»": {
    /**
     * 响应实体
     */
    data?: definitions["User"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ClassMemberPk: {
    /**
     * 班级Id
     */
    classId?: string;
    /**
     * 学员Id
     */
    userId?: string;
  };
  "BaseResponseBody«List«StuTool»»": {
    /**
     * 响应实体
     */
    data?: definitions["StuTool"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«List«SecondTaskFlow»»": {
    /**
     * 响应实体
     */
    data?: definitions["SecondTaskFlow"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  CompleteBusinessOptimizeReq: {
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  BuildBusinessDescribeRes: {
    /**
     * 描述集合
     */
    businessDescribeList?: definitions["BusinessDescribe"][];
    /**
     * 描述类型
     */
    type?: string;
  };
  ClassMember: {
    /**
     * 班级Id@Transient
     */
    classId?: string;
    classMemberPk?: definitions["ClassMemberPk"];
    /**
     * 班级名称 @Transient
     */
    className?: string;
    /**
     * 是否禁用 @Transient
     */
    disable?: boolean;
    /**
     * 学生头像 @Transient
     */
    headPath?: string;
    /**
     * 学生名称 @Transient
     */
    name?: string;
    /**
     * 教师账号 @Transient
     */
    teacherCodes?: string;
    /**
     * 教师名称 @Transient
     */
    teacherNames?: string;
    /**
     * 学员Id@Transient
     */
    userId?: string;
  };
  MergeIndexRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 第一阶段指标集合
     */
    mergeFirstStageIndexList?: definitions["MergeFirstStageIndexRequest"][];
    /**
     * 第二阶段指标集合
     */
    mergeSecondStageIndexList?: definitions["MergeSecondStageIndexRequest"][];
  };
  AddStuTaskWorkFlowReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    inParallel?: boolean;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    merge?: boolean;
    /**
     * 序号
     */
    seq?: number;
    /**
     * 学生业务id
     */
    stuBusinessId?: string;
    /**
     * 学生第二阶段流程id
     */
    stuSecondTaskFlowId?: string;
    /**
     * 第一阶段任务流程id
     */
    taskFlowId?: string;
  };
  MergeTaskMapDepartmentRequest: {
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 办事流程集合
     */
    taskWorkFlowList?: definitions["MergeTaskWorkFlowRequest"][];
  };
  WebLink: {
    createTime?: string;
    /**
     * 创建id
     */
    createUserId?: string;
    /**
     * 分配者姓名 非持久化
     */
    createUserName?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 链接
     */
    link?: string;
    /**
     * 序号
     */
    seq?: number;
    /**
     * 标题
     */
    title?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "公共REST返回Body对象«List«BusinessType»»": {
    /**
     * 响应实体
     */
    data?: definitions["BusinessType"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeIntoBusinessReq: {
    /**
     * 合并业务集合
     */
    buildBusinessReqs?: definitions["BuildBusinessReq"][];
    /**
     * 业务类型id
     */
    businessTypeId?: string;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 名称
     */
    name?: string;
  };
  "Page«UserLoginHistory»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["UserLoginHistory"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  QueryByIdRequest: {
    /**
     * 数据id
     */
    id?: string;
  };
  UpdateMaterialsRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 材料描述集合
     */
    describeRequestList?: definitions["MergeMaterialsDescribeRequest"][];
    /**
     * 数据id
     */
    id?: string;
    materialsTypeId?: string;
    materialsTypeName?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 初始状态
     */
    originalState?: string;
    /**
     * 路径
     */
    path?: string;
    /**
     * 有效时间
     */
    validTime?: number;
  };
  "BaseResponseBody«WebLink»": {
    /**
     * 响应实体
     */
    data?: definitions["WebLink"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  DepartmentBenefit: {
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 二级指标名称
     */
    secondStageIndexId?: string;
    /**
     * 工具id
     */
    toolId?: string;
    /**
     * 工具名称
     */
    toolName?: string;
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 权重
     */
    weight?: number;
  };
  QueryBusinessTypeRequest: {
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  MergeToolRequest: {
    /**
     * 耗费人力
     */
    consumeManpower?: number;
    /**
     * 耗费物力
     */
    consumeMaterial?: number;
    /**
     * 耗费技术
     */
    consumeTechnology?: number;
    /**
     * 耗费时间
     */
    consumeTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 执行强度 初始值
     */
    executeInitValue?: number;
    /**
     * 执行强度 最大值
     */
    executeMaxValue?: number;
    /**
     * 执行强度 最小值
     */
    executeMinValue?: number;
    /**
     * 执行资金
     */
    executeMoney?: number;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 工具简介
     */
    info?: string;
    /**
     * 等级
     */
    level?: string;
    /**
     * 列表标题
     */
    listTitle?: string;
    /**
     * 工具名称
     */
    name?: string;
    /**
     * 图片路径
     */
    path?: string;
    /**
     * 属性
     */
    property?: string;
    /**
     * 购买资金
     */
    purchaseMoney?: number;
    /**
     * 节约行政成本
     */
    saveCost?: number;
    /**
     * 状态
     */
    state?: string;
    /**
     * 工具类型
     */
    type?: string;
  };
  BatchDeletingRequest: {
    /**
     * id数组
     */
    ids: definitions["JSONArray"];
  };
  "公共REST返回Body对象«List«TaskFlow»»": {
    /**
     * 响应实体
     */
    data?: definitions["TaskFlow"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StuSecondTaskFlow: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 第二阶段 并联部门集合
     */
    secondInParallelDepResList?: definitions["StuSecondInParallelDepRes"][];
    /**
     * 序号
     */
    seq?: number;
    /**
     * 当前部门 办事流程
     */
    stuSecondTaskWorkFlowList?: definitions["StuSecondTaskWorkFlow"][];
    /**
     * 第一阶段任务流程id
     */
    taskFlowId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "公共REST返回Body对象«Page«Class»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«Class»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«List«ExperimentMember»»": {
    /**
     * 响应实体
     */
    data?: definitions["ExperimentMember"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  GetBusinessInfoReq: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 学生业务id
     */
    stuBusinessId?: string;
  };
  "公共REST返回Body对象«Business»": {
    /**
     * 响应实体
     */
    data?: definitions["Business"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«PageResponse«BackupMaterial»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«BackupMaterial»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "PageResponse«BackupMaterial»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["BackupMaterial"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "PageResponse«WebLink»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["WebLink"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  QueryPageIncidentRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 查询.页号
     */
    pageNo?: number;
    /**
     * 查询.页大小
     */
    pageSize?: number;
  };
  "公共REST返回Body对象«List«MergeTaskBackgroundRequest»»": {
    /**
     * 响应实体
     */
    data?: definitions["MergeTaskBackgroundRequest"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  BuildMaterialsRequest: {
    /**
     * 材料id
     */
    materialsId?: string;
    /**
     * 材料名称
     */
    materialsName?: string;
  };
  TaskMapDepartmentRes: {
    /**
     * 业务类别
     */
    businessTypeId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 办事流程集合
     */
    taskWorkFlowList?: definitions["TaskWorkFlow"][];
  };
  AddUserRequest: {
    /**
     * 账号
     */
    code?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 是否也是教师
     */
    isTeacher?: string;
    /**
     * 注册姓名
     */
    name?: string;
  };
  Tool: {
    /**
     * 耗费人力
     */
    consumeManpower?: number;
    /**
     * 耗费物力
     */
    consumeMaterial?: number;
    /**
     * 耗费技术
     */
    consumeTechnology?: number;
    /**
     * 耗费时间
     */
    consumeTime?: number;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 执行强度 初始值
     */
    executeInitValue?: number;
    /**
     * 执行强度 最大值
     */
    executeMaxValue?: number;
    /**
     * 执行强度 最小值
     */
    executeMinValue?: number;
    /**
     * 执行资金
     */
    executeMoney?: number;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 工具简介
     */
    info?: string;
    /**
     * 等级
     */
    level?: string;
    /**
     * 列表标题
     */
    listTitle?: string;
    /**
     * 工具名称
     */
    name?: string;
    /**
     * 图片路径
     */
    path?: string;
    /**
     * 属性
     */
    property?: string;
    /**
     * 购买资金
     */
    purchaseMoney?: number;
    /**
     * 节约行政成本
     */
    saveCost?: number;
    /**
     * 状态
     */
    state?: string;
    /**
     * 工具类型
     */
    type?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  ChangeUserSignatureRequest: {
    /**
     * 账号
     */
    code?: string;
    /**
     * 用户名称
     */
    name?: string;
    /**
     * 个人签名
     */
    personalSignature?: string;
  };
  SaveMaterialsTypeRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 名称
     */
    name?: string;
  };
  ExportReportReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 学生id
     */
    userId?: string;
  };
  Experiment: {
    /**
     * 班级id
     */
    classId?: string;
    /**
     * 班级名称 @Transient
     */
    className?: string;
    /**
     * 创建时间
     */
    createTime?: string;
    /**
     * 创建用户id
     */
    createUserId?: string;
    /**
     * 创建用户名称 @Transient
     */
    createUserName?: string;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 自定义名称 @Transient
     */
    customCaseName?: string;
    /**
     * 结束时间
     */
    endTime?: string;
    /**
     * 第一阶段总时间
     */
    firstTotalTime?: number;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 第二阶段总时间
     */
    secondTotalTime?: number;
    /**
     * 开始时间
     */
    startTime?: string;
    /**
     * 进行中/已结束
     */
    toState?: "进行中" | "已结束" | "未开始";
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 查看答案
     */
    viewAnswer?: boolean;
    /**
     * 查看报告
     */
    viewReport?: boolean;
  };
  "BaseResponseBody«BPhotoInfo»": {
    /**
     * 响应实体
     */
    data?: definitions["BPhotoInfo"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  AssessRes: {
    /**
     * 评估集合
     */
    assessList?: definitions["Assess"][];
    /**
     * 阶段
     */
    stage?: string;
  };
  "PageResponse«ProfessionalTerm»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["ProfessionalTerm"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "PageResponse«ExperimentMember»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["ExperimentMember"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  SecondStageWeightRes: {
    /**
     * 指标id
     */
    secondStageIndexId?: string;
    /**
     * 第二阶段指标名称
     */
    secondStageIndexName?: string;
    /**
     * 工具权重集合
     */
    toolWeightList?: definitions["ToolWeight"][];
  };
  "BaseResponseBody«List«TaskBackground»»": {
    /**
     * 响应实体
     */
    data?: definitions["TaskBackground"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«Page«User»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«User»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  VersionResult: {
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 版本号
     */
    version?: string;
  };
  BuildStuBusinessRes: {
    /**
     * 业务类别Id
     */
    businessTypeId?: string;
    /**
     * 业务类别名称
     */
    businessTypeName?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 学生业务集合
     */
    stuBusinessList?: definitions["StuBusiness"][];
  };
  "公共REST返回Body对象«List«Materials»»": {
    /**
     * 响应实体
     */
    data?: definitions["Materials"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  QueryBusinessMergeReq: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
  };
  "公共REST返回Body对象«List«Business»»": {
    /**
     * 响应实体
     */
    data?: definitions["Business"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeStuBusinessReq: {
    /**
     * 业务类别id
     */
    businessTypeId?: string;
    /**
     * 办理费用
     */
    expense?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 办理指南集合
     */
    guideDescribeList: definitions["StuBusinessDescribeReq"][];
    /**
     * 办理周期
     */
    manageConsumeTime?: number;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 反馈材料
     */
    materials?: string;
    /**
     * 所需材料
     */
    materialsType?: string;
    /**
     * 合并业务名称
     */
    name?: string;
    /**
     * 合并业务集合
     */
    stuBusinessReqList?: definitions["StuBusinessReq"][];
  };
  CompleteTaskReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 任务流程
     */
    taskFlowId?: string;
  };
  BaseUserCodeRequest: {
    /**
     * 账号
     */
    code?: string;
  };
  User: {
    /**
     * 角色.是否是管理员
     */
    admin?: boolean;
    /**
     * 年龄
     */
    age?: number;
    /**
     * 班级名称
     */
    className?: string;
    /**
     * 代码
     */
    code?: string;
    /**
     * 创建(注册)时间
     */
    createTime?: string;
    /**
     * 是否禁用
     */
    disable?: boolean;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 个人头像相对地址
     */
    headImagePath?: string;
    /**
     * 个人主页
     */
    homePage?: string;
    /**
     * 最近登录地址
     */
    lastestLoginAddr?: string;
    /**
     * 最近登录IP
     */
    lastestLoginIp?: string;
    /**
     * 最近登录时间
     */
    lastestLoginTime?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 昵称
     */
    nickname?: string;
    /**
     * 生日
     */
    personalSignature?: string;
    /**
     * 个人简介
     */
    resume?: string;
    /**
     * 教育水平
     */
    selfIntroduction?: string;
    /**
     * 性别:0:女;1:男
     */
    sex?: number;
    /**
     * 角色.是否是学生
     */
    student?: boolean;
    /**
     * 角色.是否是教师
     */
    teacher?: boolean;
    /**
     * 职业
     */
    title?: string;
  };
  StuBusiness: {
    /**
     * 是否可删
     */
    allowDelete?: boolean;
    /**
     * 原业务id(教师端)
     */
    businessId?: string;
    /**
     * 原业务类别id(教师端)
     */
    businessTypeId?: string;
    /**
     * 业务类别名称 @Transient
     */
    businessTypeName?: string;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 是否是 并联业务
     */
    inParallelBusiness?: boolean;
    /**
     * 并联业务Id
     */
    inParallelBusinessId?: string;
    /**
     * 是否参与并联
     */
    joinInParallel?: boolean;
    /**
     * 是否参与合并
     */
    joinMerge?: boolean;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称
     */
    mapDepartmentName?: string;
    /**
     * 合并业务反馈材料  @Transient
     */
    materials?: string;
    /**
     * 合并业务所需材料  @Transient
     */
    materialsType?: string;
    /**
     * 是否是 合并业务
     */
    mergeBusiness?: boolean;
    /**
     * 合并业务Id
     */
    mergeBusinessId?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 业务 合并/并联 子元素集合 @Transient
     */
    stuBusinessList?: definitions["StuBusiness"][];
    /**
     * 第一阶段任务流程id
     */
    taskFlowId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  ToolBenefitRes: {
    /**
     * 部门效益集合
     */
    departmentBenefitList?: definitions["DepartmentBenefit"][];
    /**
     * 工具id
     */
    toolId?: string;
    /**
     * 工具名称
     */
    toolName?: string;
  };
  LoginRequest: {
    cas?: boolean;
    /**
     * 用户号
     */
    code: string;
    /**
     * 密码
     */
    password: string;
  };
  "BaseResponseBody«PageResponse«WebLink»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«WebLink»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeTaskFlowRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 流程名称
     */
    name?: string;
    /**
     * 办事流程部门集合
     */
    taskMapDepartmentList?: definitions["MergeTaskMapDepartmentRequest"][];
  };
  "Page«User»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["User"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "公共REST返回Body对象«PageResponse«Experiment»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«Experiment»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "Page«Class»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["Class"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  QueryListTaskBackgroundRequest: {
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 类型
     */
    type?: string;
  };
  MergeProfessionalTermReq: {
    /**
     * 解释
     */
    content: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 名词
     */
    noun: string;
    /**
     * 序号
     */
    seq: number;
  };
  "PageResponse«Incident»": {
    bottomPageNo?: number;
    /**
     * 结果.数据列表
     */
    list?: definitions["Incident"][];
    nextPageNo?: number;
    /**
     * 页号
     */
    pageNo?: number;
    /**
     * 每页多少条记录
     */
    pageSize?: number;
    previousPageNo?: number;
    topPageNo?: number;
    totalPages?: number;
    /**
     * 查询记录总数
     */
    totalRecords?: number;
  };
  "公共REST返回Body对象«BusinessInParallel»": {
    /**
     * 响应实体
     */
    data?: definitions["BusinessInParallel"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  MergeBusinessFlowForm: {
    /**
     * 后表单
     */
    afterForm: string;
    /**
     * 前表单
     */
    beforeForm: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 名称
     */
    name: string;
  };
  IndexInfluence: {
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 事件id
     */
    incidentId?: string;
    /**
     * 数量
     */
    num?: number;
    /**
     * 选项id
     */
    operatingOptionId?: string;
    /**
     * 结果
     */
    result?: string;
    /**
     * 第二阶段指标图标
     */
    secondStageIndexIcon?: string;
    /**
     * 第二阶段指标id
     */
    secondStageIndexId?: string;
    /**
     * 第二阶段指标名称
     */
    secondStageIndexName?: string;
    /**
     * 第二阶段指标单位
     */
    secondStageIndexUnit?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  MergeOperatingOptionRequest: {
    /**
     * 选项内容
     */
    content?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 选项关联数据 集合
     */
    operatingOptionDataList?: definitions["MergeIndexInfluenceRequest"][];
  };
  "公共REST返回Body对象«PageResponse«Incident»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«Incident»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  StuFlowBusinessTypeOptionRes: {
    /**
     * 业务类型id
     */
    businessTypeId?: string;
    /**
     * 业务类型名称
     */
    businessTypeName?: string;
    /**
     * 学生业务集合
     */
    stuBusinessList?: definitions["StuBusiness"][];
  };
  "公共REST返回Body对象«List«BusinessMerge»»": {
    /**
     * 响应实体
     */
    data?: definitions["BusinessMerge"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "公共REST返回Body对象«List«DeployResultRes»»": {
    /**
     * 响应实体
     */
    data?: definitions["DeployResultRes"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  JSONArray: { [key: string]: any };
  ProfessionalTerm: {
    /**
     * 解释
     */
    content?: string;
    createTime?: string;
    /**
     * 创建id
     */
    createUserId?: string;
    /**
     * 分配者姓名 非持久化
     */
    createUserName?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 名词
     */
    noun?: string;
    /**
     * 序号
     */
    seq?: number;
    /**
     * 用户id
     */
    userId?: string;
  };
  OperatingOption: {
    /**
     * 选项内容
     */
    content?: string;
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 事件id
     */
    incidentId?: string;
    /**
     * 选项关联指标集合 @Transient
     */
    operatingOptionDataList?: definitions["IndexInfluence"][];
    /**
     * 用户id
     */
    userId?: string;
  };
  SecondStageBenefitRes: {
    /**
     * 指标id
     */
    secondStageIndexId?: string;
    /**
     * 第二阶段指标名称
     */
    secondStageIndexName?: string;
    /**
     * 工具效益集合
     */
    toolBenefitResList?: definitions["ToolBenefitRes"][];
  };
  "BaseResponseBody«List«TaskFlow»»": {
    /**
     * 响应实体
     */
    data?: definitions["TaskFlow"][];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«Page«UserLoginHistory»»": {
    /**
     * 响应实体
     */
    data?: definitions["Page«UserLoginHistory»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  "BaseResponseBody«PageResponse«ProfessionalTerm»»": {
    /**
     * 响应实体
     */
    data?: definitions["PageResponse«ProfessionalTerm»"];
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ToolWeight: {
    /**
     * 创建时间
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 二级指标名称
     */
    secondStageIndexId?: string;
    /**
     * 工具id
     */
    toolId?: string;
    /**
     * 工具名称
     */
    toolName?: string;
    /**
     * 用户id
     */
    userId?: string;
    /**
     * 权重
     */
    weight?: number;
  };
  MergeRegionMap: {
    /**
     * 部门集合
     */
    batchMergeMapDepartmentReqs?: definitions["BatchMergeMapDepartmentReq"][];
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 数据id
     */
    id?: string;
    /**
     * 地图路径
     */
    path?: string;
  };
  SecondTaskWorkFlow: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 业务名称 @Transient
     */
    businessName?: string;
    /**
     * 办结材料集合 @Transient
     */
    concludeMaterialsList?: definitions["MaterialsRelationRes"][];
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    inParallel?: boolean;
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称 @Transient
     */
    mapDepartmentName?: string;
    merge?: boolean;
    /**
     * 所需材料集合  @Transient
     */
    requiredMaterialsList?: definitions["MaterialsRelationRes"][];
    /**
     * 第二阶段流程id
     */
    secondTaskFlowId?: string;
    /**
     * 序号
     */
    seq?: number;
    /**
     * 第一阶段任务流程id
     */
    taskFlowId?: string;
    /**
     * 用户id
     */
    userId?: string;
  };
  "公共REST返回Body对象«boolean»": {
    /**
     * 响应实体
     */
    data?: boolean;
    /**
     * 异常信息
     */
    message?: string;
    /**
     * 请求是否成功
     */
    success: boolean;
  };
  ChooseOptionReq: {
    /**
     * 实训id
     */
    experimentId?: string;
    /**
     * 事件id
     */
    incidentId?: string;
    /**
     * 事件记录id
     */
    incidentRecordId?: string;
    /**
     * 事件选项id
     */
    operatingOptionId?: string;
  };
  AllocationClass: {
    /**
     * 班级学生集合
     */
    classMemberList?: definitions["ClassMember"][];
    /**
     * 禁用
     */
    disable?: boolean;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 班级名称
     */
    name?: string;
    /**
     * 备注
     */
    remarks?: string;
    /**
     * 学生人数 @Transient
     */
    stuNum?: number;
    /**
     * 教师账号
     */
    teacherCode?: string;
    /**
     * 老师ID @Transient
     */
    teacherCodes?: string;
    /**
     * 老师名称 @Transient
     */
    userNames?: string;
    /**
     * 是否是教师、管理员专用班级
     */
    vipClass?: boolean;
  };
  Incident: {
    /**
     * 创建事件
     */
    createTime?: number;
    /**
     * 自定义案例id
     */
    customCaseId?: string;
    /**
     * 主键ID
     */
    id?: string;
    /**
     * 事件描述
     */
    incidentDescribe?: string;
    /**
     * 事件类型
     */
    incidentType?: string;
    /**
     * 指标影响集合 @Transient
     */
    indexInfluenceList?: definitions["IndexInfluence"][];
    /**
     * 部门id
     */
    mapDepartmentId?: string;
    /**
     * 部门名称 非持久化
     */
    mapDepartmentName?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 选项集合  @Transient
     */
    operatingOptionList?: definitions["OperatingOption"][];
    /**
     * 图片路径
     */
    path?: string;
    /**
     * 第二阶段指标id（条件公式中的变量）
     */
    secondStageIndexId?: string;
    /**
     * 第二阶段指标名称 非持久化
     */
    secondStageIndexName?: string;
    /**
     * 显示公式
     */
    showFormula?: string;
    /**
     * 条件公式
     */
    targetFormula?: string;
    /**
     * 触发条件
     */
    triggerCondition?: string;
    /**
     * 触发时间
     */
    triggerTime?: number;
    /**
     * 用户id
     */
    userId?: string;
  };
  QueryListBenefitRequest: {
    /**
     * 自定义id
     */
    customCaseId?: string;
    /**
     * 第二阶段指标id
     */
    secondStageIndexId?: string;
  };
  MaterialsRelationRes: {
    /**
     * 业务id
     */
    businessId?: string;
    /**
     * 材料id
     */
    materialsId?: string;
    /**
     * 材料名称
     */
    materialsName?: string;
    /**
     * 类型
     */
    type?: string;
  };
}
